name: Deploy Laravel to DOM Cloud 

on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload Laravel project to DOM Cloud
        uses: appleboy/scp-action@master
        with:
          host: osk.domcloud.co
          username: ecommerce-drawing
          password: ${{ secrets.DOMCLOUD_PASS }}
          source: "."
          target: "/home/ecommerce-drawing/public_html"
          strip_components: 0
          overwrite: true
          rm: false
          exclude: |
            .git*
            node_modules
            storage/logs/*
            vendor

      - name: Run Laravel setup commands via SSH
        uses: appleboy/ssh-action@master
        with:
          host: osk.domcloud.co
          username: ecommerce-drawing
          password: ${{ secrets.DOMCLOUD_PASS }}
          script: |
            cd public_html
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force || true
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan storage:link
            echo "âœ… Deployment success to DOM Cloud!"
